# Generated by Django 6.0.7 on 2026-07-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_alimento', models.CharField(max_length=150)),
                ('quantidade', models.CharField(max_length=50)),
                ('data_validade', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='doacoes_fotos/')),
                ('tipo_armazenamento', models.CharField(blank=True, max_length=150, null=True)),
                ('horario_retirada', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservada', 'Reservada'), ('coletada', 'Coletada'), ('entregue', 'Entregue')], default='disponivel', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
